 PROGRAM driver_fIMS

 USE IMSaggregate_mod

 IMPLICIT NONE

 include 'mpif.h'

 INTEGER :: IDIM, JDIM,  NUM_TILES
 INTEGER :: LENSFC, IVEGSRC,  IERR
 INTEGER :: NPROCS, MYRANK, NUM_THREADS, NUM_PARTHDS 

! 
 Integer             :: num_subgrd_ims_cels, num_assim_steps
 CHARACTER(LEN=10)   :: DATE_STR ! YYYYMMDDHH
 CHARACTER(LEN=500)  :: IMS_SNOWCOVER_PATH, IMS_INDEXES_PATH 

 NAMELIST/fIMS/  IDIM,JDIM,date_str, num_subgrd_ims_cels, IMS_SNOWCOVER_PATH, IMS_INDEXES_PATH

! model setup 
 DATA NUM_TILES/6/
! snow DA  defaults
 DATA num_subgrd_ims_cels/30/
 DATA IMS_SNOWCOVER_PATH/'        '/
 DATA IMS_INDEXES_PATH/'        '/

 CALL MPI_INIT(IERR)
 CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NPROCS, IERR)
 CALL MPI_COMM_RANK(MPI_COMM_WORLD, MYRANK, IERR)

 NUM_THREADS = NUM_PARTHDS()

 PRINT*
 PRINT*,"STARTING fIMS PROGRAM ON RANK ", MYRANK
 PRINT*,"RUNNING WITH ", NPROCS, "TASKS"
 PRINT*,"AND WITH ", NUM_THREADS, " THREADS."

 PRINT*
 PRINT*,"READ fIMS NAMELIST."

 CALL BAOPENR(360, "fIMS.nml", IERR)
 READ(360, NML=fIMS)
 IF (MYRANK==0) WRITE(6,fIMS)

 LENSFC = IDIM*JDIM ! TOTAL NUMBER OF POINTS FOR THE CUBED-SPHERE TILE

 PRINT*,"calling calcfIMS on RANK" , MYRANK
 CALL MPI_BARRIER(MPI_COMM_WORLD, IERR)

 CALL calculate_IMS_fSCA(NUM_TILES, MYRANK, NPROCS, IDIM, JDIM, &
                      LENSFC, num_subgrd_ims_cels, date_str,&
                      IMS_SNOWCOVER_PATH, IMS_INDEXES_PATH)
 PRINT*,"calcfIMS returned on RANK", MYRANK

 CALL MPI_BARRIER(MPI_COMM_WORLD, IERR)
 CALL MPI_FINALIZE(IERR)

 END PROGRAM driver_fIMS
